apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: buzzbingo-api-v000
  namespace: buzzbingo
  labels:
    app: buzzbingo
    stack: api
    version: v000
    io.kompose.service: api
spec:
  replicas: 1
  selector:
      matchLabels:
        replication-controller: buzzbingo-api-v000
  template:
    metadata:
      labels:
        io.kompose.service: api
        replication-controller: buzzbingo-api-v000
    spec:
      containers:
      - image: emjburns/buzzbingo-api:latest
        imagePullPolicy: Always
        env:
        name: api
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
