apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: buzzbingo-redis-v000
  namespace: buzzbingo
  labels:
    app: buzzbingo
    stack: redis
    version: v000
    io.kompose.service: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      replication-controller: buzzbingo-redis-v000
  template:
    metadata:
      labels:
        io.kompose.service: redis
        replication-controller: buzzbingo-redis-v000
    spec:
      containers:
      - image: redis
        name: redis
        ports:
        - containerPort: 6379
        resources: {}
      restartPolicy: Always
