version: '2'
services:
  api:
    build: .
    ports:
    - "8080:8080"
    links:
    - redis
    environment:
    - DOCKER=true
  redis:
      image: redis
      ports:
      - "6379"
  ui:
    build: ./ui
    ports:
    - "3000:3000"
    links:
    - api
