apiVersion: v1
kind: Service
metadata:
  namespace: buzzbingo
  creationTimestamp: null
  labels:
    io.kompose.service: redis
    app: buzzbingo
    stack: redis
  name: buzzbingo-redis

spec:
  ports:
  - name: "redis"
    port: 6379
    targetPort: 6379
  selector:
    io.kompose.service: redis
status:
  loadBalancer: {}
