apiVersion: v1
kind: Service
metadata:
  namespace: buzzbingo
  creationTimestamp: null
  labels:
    io.kompose.service: ui
    app: buzzbingo
    stack: ui
  name: buzzbingo-ui
spec:
  ports:
  - name: "ui"
    port: 80
    targetPort: 3000
  selector:
    io.kompose.service: ui
  type: LoadBalancer
status:
  loadBalancer: {}
